---
title: "R Notebook"
output: html_notebook
---

## Setup

```{r}
library(tidyverse)
library(readxl)
library(corrplot)
library(ggthemes)
library(stargazer)

acs1 <- read.csv("C:/Users/asbru/Documents/Emory/Advanced Mangerial Econ & Data Analytics/Assignment 2/Data/2014-american-community-survey/ss14pusa.csv")
acs2 <- read.csv("C:/Users/asbru/Documents/Emory/Advanced Mangerial Econ & Data Analytics/Assignment 2/Data/2014-american-community-survey/ss14pusb.csv")

acsfull <-
  acs1 %>%
  union(acs2)

```

```{r}




# acsnew %>%
#   ungroup(SEX,MAR) %>%
#   count(SERIALNO)

```


## Wrangle

```{r}

# head(acs2)


acsmaritalstatus <-
  acsfull %>%
  filter(MAR %in% c(1,3)) %>%
  select(c(AGEP,MAR,WAGP,COW,RAC1P,HISP,SEX,SCHL,NAICSP,FMARHDP,MARHD,MARHYP,MARHD)) %>%
  mutate(sexlabel = case_when(SEX == 1 ~ "male",
                              SEX == 2 ~ "female")) %>%
  mutate(marstatus = case_when(MAR == 1 ~ "married",
                               MAR == 3 ~ "divorced")) %>%
  mutate(race = case_when(RAC1P == 1 ~ "White",
                          RAC1P == 2 ~ "black",
                          RAC1P == 3 ~ "native",
                          RAC1P == 4 ~ "native",
                          RAC1P == 5 ~ "native",
                          RAC1P == 6 ~ "asian",
                          RAC1P == 7 ~ "hawaiian",
                          RAC1P == 8 ~ "other",
                          RAC1P == 9 ~ "mixed")) %>%
  mutate(classstatus = case_when(COW == "b" ~ "N/A",
                                 COW == 1 ~ "For-Profit",
                                 COW == 2 ~ "Non-Profit",
                                 COW == 3 ~ "Govt",
                                 COW == 4 ~ "Govt",
                                 COW == 5 ~ "Govt",
                                 COW == 6 ~ "Self-Employed",
                                 COW == 7 ~ "Self-Employed",
                                 COW == 8 ~ "Working without Pay in Family Biz/Farm",
                                 COW == 9 ~ "Unemployed")) %>%
  mutate(education = case_when(SCHL == "bb" ~ 0,
                               SCHL == 01 ~ 0,
                               SCHL == 02 ~ 0,
                               SCHL == 03 ~ 0,
                               SCHL == 04 ~ 1,
                               SCHL == 05 ~ 2,
                               SCHL == 06 ~ 3,
                               SCHL == 07 ~ 4,
                               SCHL == 08 ~ 5,
                               SCHL == 09 ~ 6,
                               SCHL == 10 ~ 7,
                               SCHL == 11 ~ 8,
                               SCHL == 12 ~ 9,
                               SCHL == 13 ~ 10,
                               SCHL == 14 ~ 11,
                               SCHL == 15 ~ 11.5,
                               SCHL == 16 ~ 12,
                               SCHL == 17 ~ 11.75,
                               SCHL == 18 ~ 12.5,
                               SCHL == 19 ~ 13,
                               SCHL == 20 ~ 14,
                               SCHL == 21 ~ 16.5,
                               SCHL == 22 ~ 18,
                               SCHL == 23 ~ 19.5,
                               SCHL == 24 ~ 23)) %>%
  mutate(exp = AGEP - education - 5) %>%
  mutate(expsqd = exp^2) %>%
  mutate(lnwages = log(WAGP))

# smallsetb <-
#   acsmaritalstatus %>%
#   filter(marstatus == "divorced")
# 
# write.csv(smallsetb, file = "C:/Users/asbru/Documents/Emory/Advanced Mangerial Econ & Data Analytics/Assignment 2/smallsetb.csv")
#   
#   
#   acsnew <- 
#   acsmaritalstatus %>%
#   group_by(SEX,MAR) %>%
#   summarize(avewagp = mean(WAGP)) 

```

##Correlation

```{r}


correlation <- 
  acsmaritalstatus %>%
  select(c(JWTR,LANX,MAR,SCHL))
M <- 
  cor(correlation)
# png(file="corr.png", res=300, width=4500, height=4500)
corrplot(M, method = "shade", number.cex = 1, tl.cex = 1, title = "All Positions", mar=c(0,0,1,0))
```

##Histograms


```{r}
hist1<-
  acsmaritalstatus %>%
  ggplot( aes(x=education)) +
  geom_histogram(bins = 24)
ggplotly(hist1)

```


##Model 1

```{r}

LinearModel1 <- lm(WAGP ~ education 
                   + exp 
                   + expsqd
                   + marstatus
                   + classstatus
                   + sexlabel
                   + MARHD
                   + race
                   # + COW
                   ,data = acsmaritalstatus)
summary(LinearModel1)


```

##Subset Data for Model

```{r}

ACS_divorced_married_men <- 
  acsmaritalstatus %>%
  filter(sexlabel == "male")
  
ACS_divorced_married_women <- 
  acsmaritalstatus %>%
  filter(sexlabel == "female")

ACS_divorced <- 
  acsmaritalstatus %>%
  filter(marstatus == "divorced")
  
ACS_married <- 
  acsmaritalstatus %>%
  filter(marstatus == "married")
  
  

```


##Model

```{r}

#ALL
LinearModel1 <- lm(WAGP ~ education 
                   + exp 
                   + expsqd
                   + marstatus
                   + classstatus
                   + sexlabel
                   + MARHD
                   + race
                   # + COW
                   ,data = acsmaritalstatus)
summary(LinearModel1)

#Only Men


LinearModel_Men <- lm(WAGP ~ education 
                   + exp 
                   + expsqd
                   + marstatus
                   + classstatus
                   # + sexlabel
                   + MARHD
                   + race
                   ,data = ACS_divorced_married_men)
#Only Women


LinearModel_Women <- lm(WAGP ~ education 
                   + exp 
                   + expsqd
                   + marstatus
                   + classstatus
                   # + sexlabel
                   + MARHD
                   + race
                   ,data = ACS_divorced_married_women)
#Only Divorced


LinearModel_Divorced <- lm(WAGP ~ education 
                   + exp 
                   + expsqd
                   # + marstatus
                   + classstatus
                   + sexlabel
                   + MARHD
                   + race
                   ,data = ACS_divorced)
#Only Married


LinearModel_Married <- lm(WAGP ~ education 
                   + exp 
                   + expsqd
                   # + marstatus
                   + classstatus
                   + sexlabel
                   + MARHD
                   + race
                   ,data = ACS_married)

summary(LinearModel_Men)
summary(LinearModel_Women)
summary(LinearModel_Divorced)
summary(LinearModel_Married)

```

##Stargazer

```{r mylatextable, results = "asis"}
stargazer(LinearModel_Divorced, type = "latex")
```

